### ISSUE TITLE
Request: Add and Delete Statement blocks

### ISSUE THREAD

**Issue by mcolatosti** [totoleon/AwsPolicy#3]
Looks to be a well designed module.  It would be awesome to have additional CRUD operations supported.  You've completed "Update", but the creation and removal of statement blocks would be immensely useful.

**Comment by reidca** [comment]
> Looks to be a well designed module. It would be awesome to have additional CRUD operations supported. You've completed "Update", but the creation and removal of statement blocks would be immensely useful.

I echo this, I was looking for something to add a new statement block to an existing policy but I don't believe this is capable of that today. Would be very useful.

**Comment by reidca** [comment]
I have managed to achieve updating a bucket policy using a combination of this resource and some standard boto s3 client code. 

It's wrapped up in a lambda backed custom resource but hopefully this could be helpful to someone.

I had to add a function to test whether the bucket already had a policy before using this otherwise an exception would be thrown.



```
def test_bucket_policy(bucket):
    try:
        s3_client.get_bucket_policy(Bucket=bucket)
        return True
    except ClientError as error:
        if error.response["Error"]["Code"] == "NoSuchBucketPolicy":
            return False
        raise

def update_create(event, context):
    props = event['ResourceProperties']
    bucket = props["Bucket"]
    new_statement = props["Statement"]
    logger.info(f"Statement to add is: {new_statement}")
    physical_resource_ids = []
    if (test_bucket_policy(bucket)):
        logger.info(f"Found an existing bucket policy for bucket '{bucket}'...adding new statement")
        # If it already exists, load the existing bucket policy as an object
        bucket_policy = BucketPolicy(serviceModule=s3_client, resourceIdentifer=bucket)
        
        for statement_entry in new_statement:
            if "Sid" in statement_entry:
                sid = statement_entry["Sid"]
                existing_statement_matching_sid = bucket_policy.select_statement(sid)
                if existing_statement_matching_sid:
                    existing_statement_matching_sid.content = statement_entry
                    existing_statement_matching_sid.save()
                else:
                    bucket_policy.content["Statement"].append(statement_entry)
                physical_resource_ids.append(sid)
            else:
                raise ValueError("Missing 'Sid' in policy statement")
        bucket_policy.save()
        logger.info(f"The bucket policy for bucket '{bucket}' has been updated successfully")        
    else:
        logger.info(f"No existing bucket policy found for bucket '{bucket}' therefore one will be created")
        for statement_entry in new_statement:
            if "Sid" in statement_entry:
                sid = statement_entry["Sid"]
                physical_resource_ids.append(sid)
            else:
                raise ValueError("Missing 'Sid' in policy statement")
        
        bucket_policy = {
            'Version': '2012-10-17',
            'Statement' : new_statement}
        
        # Convert the policy from JSON dict to string
        bucket_policy = json.dumps(bucket_policy)
        s3_client.put_bucket_policy(Bucket=bucket, Policy=bucket_policy)
        logger.info(f"Bucket policy updated successfully") 
```

**Comment by SpyderDave** [comment]
@reidca I know this is pretty old. But I am trying to figure out how I can append a statement (Sid) to an existing S3 bucket policy, but I am getting nowhere fast.
What gets passed to your Lambda function?.

**Comment by reidca** [comment]
The full (and updated) code for the Lambda is:

```
import boto3
import json
from botocore.exceptions import ClientError
import logging
from awspolicy import BucketPolicy
from crhelper import CfnResource

helper = CfnResource(json_logging=False, log_level='DEBUG',
                     boto_level='CRITICAL')
logger = logging.getLogger(__name__)

try:
    # Init code goes here
    s3_client = boto3.client('s3')
    pass
except Exception as e:
    helper.init_failure(e)

def test_bucket_policy(bucket):
    try:
        s3_client.get_bucket_policy(Bucket=bucket)
        return True
    except ClientError as error:
        if error.response["Error"]["Code"] == "NoSuchBucketPolicy":
            return False
        raise

@helper.create
@helper.update
def update_create(event, context):
    props = event['ResourceProperties']
    bucket = props["Bucket"]
    new_statement = props["Statement"]
    logger.info(f"Statement to add is: {new_statement}")
    physical_resource_ids = []
    if (test_bucket_policy(bucket)):
        logger.info(f"Found an existing bucket policy for bucket '{bucket}'...adding new statement")
        # If it already exists, load the existing bucket policy as an object
        bucket_policy = BucketPolicy(serviceModule=s3_client, resourceIdentifer=bucket)
        
        for statement_entry in new_statement:
            if "Sid" in statement_entry:
                sid = statement_entry["Sid"]
                existing_statement_matching_sid = bucket_policy.select_statement(sid)
                if existing_statement_matching_sid:
                    existing_statement_matching_sid.content = statement_entry
                    existing_statement_matching_sid.save()
                else:
                    bucket_policy.content["Statement"].append(statement_entry)
                physical_resource_ids.append(sid)
            else:
                raise ValueError("Missing 'Sid' in policy statement")
        bucket_policy.save()
        logger.info(f"The bucket policy for bucket '{bucket}' has been updated successfully")        
    else:
        logger.info(f"No existing bucket policy found for bucket '{bucket}' therefore one will be created")
        for statement_entry in new_statement:
            if "Sid" in statement_entry:
                sid = statement_entry["Sid"]
                physical_resource_ids.append(sid)
            else:
                raise ValueError("Missing 'Sid' in policy statement")
        
        bucket_policy = {
            'Version': '2012-10-17',
            'Statement' : new_statement}
        
        # Convert the policy from JSON dict to string
        bucket_policy = json.dumps(bucket_policy)
        s3_client.put_bucket_policy(Bucket=bucket, Policy=bucket_policy)
        logger.info(f"Bucket policy updated successfully")    
    
    #Return the physical id which is the sids comma separated
    return ",".join(physical_resource_ids)
@helper.delete
def delete(event, context):
    """
    Place your code to handle Delete events here

    To return a failure to CloudFormation simply raise an exception, the exception message will be sent to CloudFormation Events.
    """
    props = event['ResourceProperties']
    sids = event["PhysicalResourceId"].split(",")
    bucket = props["Bucket"]
    if (test_bucket_policy(bucket)):
        for sid in sids:
            bucket_policy = BucketPolicy(serviceModule=s3_client, resourceIdentifer=bucket)
            logger.info(f"Checking whether statement sid {sid} is found in policy")
            existing_statement = bucket_policy.select_statement(sid)
            if existing_statement:
                logger.info(f"Sid {sid} found in policy...removing")
                statements = bucket_policy.content["Statement"]
                new_statements = []
                for statement in statements:
                    logger.info(f"Processing statement with sid {statement['Sid']}")
                    if statement["Sid"] == sid:
                        logger.info("Removing...")
                    else:
                        new_statements.append(statement)

                #Check to see if the there any remainng statements, if not delete the entire policy
                if len(new_statements) >0:
                    bucket_policy.content["Statement"] = new_statements
                    bucket_policy.save()
                    logger.info(f'Bucket {bucket} policy updated successfully')
                else:
                    s3_client.delete_bucket_policy(Bucket=bucket)
                    logger.info(f"Since there are no additional statemets remaining, the entire bucket policy for bucket '{bucket}' has been deleted!")
            else:
                logger.info(f"Sid {sid} not found in policy")
    else:
        logger.info(f"No existing bucket policy found for bucket '{bucket}' therefore nothing to delete")

def handler(event, context):
    """
    Main handler function, passes off it's work to crhelper's cfn_handler
    """
    helper(event, context)
```



It has dependencies on the AWS Policy resource from this repo and also the crhelper which AWS provides.

The lambda function code is created as a cloudformation custom resource which I then use like this:

```
CustomResourceLambdaBucketPolicyUpdater:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !ImportValue BucketPolicyUpdaterHelperArn
      loglevel: debug
      Bucket: !Ref Bucket
      Statement:
        - Sid: DelegateS3BucketAccess
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::123456789:root
          Action:
          - s3:ListBucket          
          Resource:          
          - !Sub 
            - arn:aws:s3:::bucketname-${environment}-${BucketNameSuffix}                  
            - environment: !FindInMap
              - EnvironmentConfigs
              - !Ref 'AWS::AccountId'
              - EnvironmentType
        - Sid: DelegateS3BucketObjectAccess
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::123456789:root
          Action:          
          - s3:GetObject
          Resource:
          - !Sub 
            - arn:aws:s3:::bucketname-${environment}-${BucketNameSuffix}/*
            - environment: !FindInMap
              - EnvironmentConfigs
              - !Ref 'AWS::AccountId'
              - EnvironmentType

```
The main point if interest here is the "Statement" block of YAML . This is passed into the Lambda function by CloudFormation. The function reads this and adds the Sids to the existing bucket policy. It is important to have Sids so the function knows whether they already exist in the bucket policy.

Does that help?
